### ISSUE TITLE
Feedback does not work with Jenkins pipelines. 

### ISSUE THREAD

**Issue by billmackie** [TransFICC/transficc-feedback#4]
My Jenkins environment is a mixture of Freestyle and Pipeline jobs. After a bit of to-ing and fro-ing (thanks for your help Tom), I managed to get Feeback to display results for some of my jobs, but others are shown as not having built(last build time 48 years ago). Further delving brought em to the view that all the successfullly reported jobs are Freestyle jobs, while the failing ones are all Pipelines.
The following stacktrace is output
16:07:04.220 [transficc-feedback-thread-5] ERROR com.transficc.tools.feedback.GetLatestJobBuildInformation - An exception occurred whilst trying to gather build information
java.lang.NullPointerException
	at com.transficc.tools.feedback.JenkinsFacade.getLatestBuildInformation(JenkinsFacade.java:95) ~[transficc-feedback-all.jar:?]
	at com.transficc.tools.feedback.GetLatestJobBuildInformation.run(GetLatestJobBuildInformation.java:57) [transficc-feedback-all.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_131]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:1.8.0_131]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_131]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:1.8.0_131]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_131]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_131]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]

I don't yet have any multi-branch pipelines, so I don't know if the same issue occurs with those.

**Comment by tom-smalls** [comment]
Thanks for the stacktrace Bill!

For one of your pipeline jobs, can you provide the last build details (feel free to email it to me if it contains anything sensitive), that are available via the Jenkins API?

To get this information for our job ```master-commit``` I would do the following:

1. Go to http://10.24.2.83:8080/job/master-commit/api/json?pretty=true
2. This would return a payload containing the following:
```
"lastBuild" : {
    "_class" : "hudson.model.FreeStyleBuild",
    "number" : 3512,
    "url" : "http://10.24.2.83:8080/job/master-commit/3512/"
  },
```
3. Go to http://10.24.2.83:8080/job/master-commit/3512/api/json?pretty=true

It seems that there is not change set information for pipeline jobs, but I am interested to see what information there is instead!

**Comment by tom-smalls** [comment]
I created a demo pipeline job in our Jenkins CI, and one thing I've noticed is ```changeSet``` appears to be called ```changeSets``` for pipeline jobs :(

**Comment by billmackie** [comment]
here’s the output from that query

output from 

http://*****************:8080/job/OpenCsd_Frontend/103/api/json?pretty=true
	
_class	"org.jenkinsci.plugins.workflow.job.WorkflowRun"
actions	
0	
_class	"hudson.model.CauseAction"
causes	
0	
_class	"hudson.triggers.TimerTrigger$TimerTriggerCause"
shortDescription	"Started by timer"
1	
2	
_class	"hudson.plugins.git.util.BuildData"
buildsByBranchName	
refs/remotes/origin/master	
_class	"hudson.plugins.git.util.Build"
buildNumber	103
buildResult	
marked	
SHA1	"0ad5279c0178231016245309bda5d893e1cbfaf5"
branch	
0	
SHA1	"0ad5279c0178231016245309bda5d893e1cbfaf5"
name	"refs/remotes/origin/master"
revision	
SHA1	"0ad5279c0178231016245309bda5d893e1cbfaf5"
branch	
0	
SHA1	"0ad5279c0178231016245309bda5d893e1cbfaf5"
name	"refs/remotes/origin/master"
lastBuiltRevision	
SHA1	"0ad5279c0178231016245309bda5d893e1cbfaf5"
branch	
0	
SHA1	"0ad5279c0178231016245309bda5d893e1cbfaf5"
name	"refs/remotes/origin/master"
remoteUrls	
0	"https://setlCIAdmin@bitbucket.org/projectluthor/setltestnet.git"
scmName	""
3	
_class	"hudson.plugins.git.GitTagAction"
4	
5	
6	
_class	"hudson.plugins.sonar.action.SonarAnalysisAction"
ceTaskId	"AV0uJFQ1luq3_7tK03d9"
installationName	"SonarQube"
new	true
skipped	false
sonarqubeDashboardUrl	"http://si-jenkins01.dev.setl.io:8081/dashboard/index/OpenCSD_FrontEnd"
7	
8	
9	
_class	"hudson.plugins.sonar.action.SonarBuildBadgeAction"
url	"http://si-jenkins01.dev.setl.io:8081/dashboard/index/OpenCSD_FrontEnd"
10	
11	
12	
13	
_class	"org.jenkinsci.plugins.workflow.job.views.FlowGraphAction"
14	
15	
artifacts	
building	false
description	
displayName	"#103"
duration	19171
estimatedDuration	23595
executor	
fullDisplayName	"OpenCSD Frontend #103"
id	"103"
keepLog	false
number	103
queueId	4416
result	"SUCCESS"
timestamp	1499717700401
url	"http://si-jenkins01.dev.setl.io:8080/job/OpenCsd_Frontend/103/"
changeSets	
nextBuild	
number	104
url	"http://si-jenkins01.dev.setl.io:8080/job/OpenCsd_Frontend/104/"
previousBuild	
number	102
url	"http://si-jenkins01.dev.setl.io:8080/job/OpenCsd_Frontend/102/"

**Comment by tom-smalls** [comment]
I've added a temporary null guard in 122b577e697b4f0fd170a208bafaef7ece707139 whilst we come up with a better solution.

Does this fix your issue?

**Comment by billmackie** [comment]
I’ll give it a try and let you know, will probably be around lunchtime

**Comment by benhyland** [comment]
@billmackie late lunch?
